<?php

namespace App\Repositories\User;

use App\Models\User as UserModel;
use App\Repositories\EloquentRepository;

class UserEloquentRepository extends EloquentRepository implements UserRepositoryInterface
{


    /**
     * get model
     *
     * @return string
     */
    public function getModel()
    {
        return UserModel::class;
    }

    public function setModel()
    {
        parent::setModel(); // TODO: Change the autogenerated stub
    }

    public function getByFilter(array $filter = [])
    {
        $query = $this->_model;

        return $query->paginate(10);
    }
}
